version: '3.3'
services:

  database:
    image: postgres:latest
    container_name: dev-postgres
    hostname: dev-postgres
    restart: always
    env_file:
      - ./env/database.env
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lin/postgresql/data
    # TODO

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    env_file:
      - ./env/pgadmin.env
    ports:
      - '5050:80'
    volumes:
      - data:/var/log/data
    # TODO

  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - '80:80'
    # TODO 

volumes:
  data: